package com.cooksys.airline.models;

// Generated May 14, 2016 4:09:48 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "airline")
public class Location implements java.io.Serializable {

	private Integer id;
	private String city;
	private String state;
	private Set<UserDestination> userDestinations = new HashSet<UserDestination>(
			0);
	private Set<UserLocation> userLocations = new HashSet<UserLocation>(0);

	public Location()
	{
	}

	public Location(String city, String state)
	{
		this.city = city;
		this.state = state;
	}

	public Location(String city, String state,
			Set<UserDestination> userDestinations,
			Set<UserLocation> userLocations)
	{
		this.city = city;
		this.state = state;
		this.userDestinations = userDestinations;
		this.userLocations = userLocations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 45)
	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<UserDestination> getUserDestinations()
	{
		return this.userDestinations;
	}

	public void setUserDestinations(Set<UserDestination> userDestinations)
	{
		this.userDestinations = userDestinations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<UserLocation> getUserLocations()
	{
		return this.userLocations;
	}

	public void setUserLocations(Set<UserLocation> userLocations)
	{
		this.userLocations = userLocations;
	}

}
