package com.cooksys.airline.models;

// Generated May 15, 2016 12:47:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "airline")
public class Location implements java.io.Serializable {

	private Integer id;
	private String city;
	private String state;
	private Set<Trip> tripsForStartLocation = new HashSet<Trip>(0);
	private Set<Trip> tripsForCurrentLocation = new HashSet<Trip>(0);
	private Set<Trip> tripsForDestinationLocation = new HashSet<Trip>(0);

	public Location()
	{
	}

	public Location(String city, String state)
	{
		this.city = city;
		this.state = state;
	}

	public Location(String city, String state, Set<Trip> tripsForStartLocation,
			Set<Trip> tripsForCurrentLocation,
			Set<Trip> tripsForDestinationLocation)
	{
		this.city = city;
		this.state = state;
		this.tripsForStartLocation = tripsForStartLocation;
		this.tripsForCurrentLocation = tripsForCurrentLocation;
		this.tripsForDestinationLocation = tripsForDestinationLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 45)
	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationByStartLocation")
	public Set<Trip> getTripsForStartLocation()
	{
		return this.tripsForStartLocation;
	}

	public void setTripsForStartLocation(Set<Trip> tripsForStartLocation)
	{
		this.tripsForStartLocation = tripsForStartLocation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationByCurrentLocation")
	public Set<Trip> getTripsForCurrentLocation()
	{
		return this.tripsForCurrentLocation;
	}

	public void setTripsForCurrentLocation(Set<Trip> tripsForCurrentLocation)
	{
		this.tripsForCurrentLocation = tripsForCurrentLocation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationByDestinationLocation")
	public Set<Trip> getTripsForDestinationLocation()
	{
		return this.tripsForDestinationLocation;
	}

	public void setTripsForDestinationLocation(
			Set<Trip> tripsForDestinationLocation)
	{
		this.tripsForDestinationLocation = tripsForDestinationLocation;
	}

}
