package com.cooksys.airline.models;

// Generated May 13, 2016 12:21:08 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TicketId generated by hbm2java
 */
@Embeddable
public class TicketId implements java.io.Serializable {

	private int userId;
	private int flightId;

	public TicketId()
	{
	}

	public TicketId(int userId, int flightId)
	{
		this.userId = userId;
		this.flightId = flightId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId()
	{
		return this.userId;
	}

	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	@Column(name = "flight_id", nullable = false)
	public int getFlightId()
	{
		return this.flightId;
	}

	public void setFlightId(int flightId)
	{
		this.flightId = flightId;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TicketId))
			return false;
		TicketId castOther = (TicketId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getFlightId() == castOther.getFlightId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getFlightId();
		return result;
	}

}
