package com.cooksys.airline.models;

// Generated May 14, 2016 4:09:48 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Trip generated by hbm2java
 */
@Entity
@Table(name = "trip", catalog = "airline")
public class Trip implements java.io.Serializable {

	private Integer id;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);
	private Set<User> users = new HashSet<User>(0);

	public Trip()
	{
	}

	public Trip(Set<Ticket> tickets, Set<User> users)
	{
		this.tickets = tickets;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "trip_ticket", catalog = "airline", joinColumns = { @JoinColumn(name = "trip_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ticket_id", nullable = false, updatable = false) })
	public Set<Ticket> getTickets()
	{
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets)
	{
		this.tickets = tickets;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "trip_user", catalog = "airline", joinColumns = { @JoinColumn(name = "trip_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers()
	{
		return this.users;
	}

	public void setUsers(Set<User> users)
	{
		this.users = users;
	}

}
